# Generated by Django 5.0.4 on 2024-05-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCategory',
            new_name='Categories',
        ),
    ]
